path:
  - .
  - core
  - common
  - modules
  - views
  - lib
jobs: 10
extensions:
  - php
exclude:
  - vendor
  - lib/vendor
  - .wordpress-org
  - dist
  - languages
  - .github
  - tests
  - .web
  - .ddev
warning: false
